### ISSUE TITLE
No error on network fail

### ISSUE THREAD

**Issue by litvinenkow** [henrya/js-jquery#7]
Hi
I'm using your plugin for getting file from my server to app via cordova. And there is no "error" event if network fails or changing from wi-fi to gsm or smthg. Just no error at all and script fails and nothing. How can i handle this? Nothing helps.

$.ajax({
                        url: url,
                        dataType: "binary",
                        .....
                        },
                        error:function() {
                            $('#loading').fadeOut();
                            $('#global_stop').hide();
                            $('#global_result').html('<span class="error">Connection error</span>');
                        }
                    }).always(function(data, textStatus, jqXHR){
                        console.log(textStatus);
                    });

This construction doesn't fire error as well. Without your plugin it works well, but i need to save binary images.

**Comment by henrya** [comment]
This issue was solved in the following commit: https://github.com/gartner/js-jquery/commit/48e95546d23b554530cb63e3eabc6fcddbd285ac
